version: '3'
services:
  opal:
    image: obiba/opal:5
    ports:
      - "8880:8080"
      - "8843:8443"
    links:
      - rock
      - mongo
      - mysqldata
    environment:
      - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MYSQLDATA_HOST=mysqldata
      - MYSQLDATA_DATABASE=opal
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=password
      - ROCK_HOSTS=rock:8085
      - CSRF_ALLOWED=datashield2.liv.ac.uk:8880,datashield2.liv.ac.uk:80,datashield2.liv.ac.uk,datashield2.liv.ac.uk:8843,datshield2.liv.ac.uk:443
    volumes:
      - /opal:/srv
  mongo:
    image: mongo:6.0
  mysqldata:
    image: mysql
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  rock:
    image: datashield/rock-base:latest
