services:
  opal:
    image: obiba/opal:5
    ports:
      - "8880:8080"
      - "8843:8443"
    links:
      - rock
      - mongo
      - mysqldata
    environment:
      - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - OPAL_DEMO_USER_NAME=demo_user
      - OPAL_DEMO_USER_PASSWORD=demo_password
      - OPAL_DEMO_PROJECT=DEMO
      - OPAL_DEMO_TABLE=CNSIM1
      - OPAL_DEMO_SOURCE_DATA_URL=https://raw.githubusercontent.com/OllyButters/ds_data/main/CNSIM/CNSIM1.csv
      - OPAL_COHORT_PROJECT=COHORT
      - OPAL_COHORT_TABLE=conditions1
      - OPAL_COHORT_SOURCE_DATA_URL=https://raw.githubusercontent.com/OllyButters/ds_data/main/synthea/conditionsa.csv
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MYSQLDATA_HOST=mysqldata
      - MYSQLDATA_DATABASE=opal
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=password
      - ROCK_HOSTS=rock:8085
      #- CSRF_ALLOWED=datashield2.liv.ac.uk:8880,datashield2.liv.ac.uk:80,datashield2.liv.ac.uk,datashield2.liv.ac.uk:8843,datshield2.liv.ac.uk:443
      - CSRF_ALLOWED=172.24.128.135:8080,172.24.128.135:8443,172.24.128.135:8880,172.24.128.135:8843,172.24.128.135:8888,172.24.128.135:8883,CSRF_ALLOWED=172.24.128.135:80
    volumes:
      - /datashield/1/opal:/srv
      - ./customise.sh:/customise.sh
    post_start:
      - command: bash -c "/customise.sh"
  mongo:
    image: mongo:6.0
  mysqldata:
    image: mysql
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  rock:
    image: datashield/rock-base:latest
